name: dleyetracking
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - certifi=2021.5.30
  - freetype=2.11.0
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - ncurses=6.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - pillow=8.3.1
  - python=3.6.13
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.39.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - about-time==3.1.1
    - alive-progress==2.1.0
    - argparse==1.4.0
    - av==10.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cycler==0.11.0
    - cysignals==1.11.2
    - cython==0.29.32
    - dataclasses==0.8
    - decorator==4.4.2
    - glfw==2.5.5
    - grapheme==0.6.0
    - idna==3.4
    - imageio==2.15.0
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - ipaddress==1.0.23
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - littleutils==0.2.2
    - matplotlib==3.3.4
    - msgpack==1.0.4
    - ndsi==1.4.4
    - networkx==2.5.1
    - numexpr==2.8.1
    - numpy==1.19.5
    - opencv-python==4.5.1.48
    - outdated==0.2.2
    - packaging==21.3
    - pandas==1.1.5
    - pandas-flavor==0.6.0
    - patsy==0.5.3
    - pingouin==0.3.12
    - pip==21.3.1
    - plotly==5.14.1
    - psutil==5.9.2
    - pupil-apriltags==1.0.4
    - pupil-detectors==2.0.1
    - pyaudio==0.2.11
    - pye3d==0.1.1
    - pyglui==1.31.0.post2
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pystan==2.19.1.1
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytz==2022.2.1
    - pywavelets==1.1.1
    - pyyaml==6.0
    - pyzmq==23.2.1
    - requests==2.27.1
    - scikit-image==0.17.2
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - seaborn==0.11.2
    - six==1.16.0
    - sortedcontainers==2.4.0
    - statsmodels==0.12.2
    - tabulate==0.8.10
    - tenacity==8.2.2
    - threadpoolctl==3.1.0
    - tifffile==2020.9.3
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - urllib3==1.26.16
    - pupil-labs-uvc
    - xarray==0.16.2
    - zeromq-pyre==0.3.4
    - zipp==3.6.0
